### ISSUE TITLE
Were can I find examples code?

### ISSUE THREAD

**Issue by spring-haru** [MathsCell/nlsic#1]
I wonder if there are Jupyter Notebooks or similar showing example usage of `nlsic`. I am especially interested in solving non-negative least squares with equality constraints.

**Comment by sgsokol** [comment]
There is a small example in R help for nlsic::nlsic function. Unfortunately, this example does not use equality constraints. However, parameters 'e' and 'eco' which define equality constraints are simple to use. 'e' is constraint matrix and 'eco' is right-hand-side of constraints. Such that `e%*%par=eco`.
One more thing. You don't say if your problem is linear or not. If it is then nlsic is an overkill. You'd better to use nlsic::lsie_ln.
Hoping this helps.

**Comment by spring-haru** [comment]
My problem is a linear regression with linear constraints and non-negative constraints of parameters. So, `lsie_ln` is the choice for me. Given that I am not really an `R` person, I should be grateful if you could show me a simple example.

**Comment by MathsCell** [comment]
Let `Ax=b`  your linear least squares regression with A m x n matrix where `m` rows > `n` columns (so `length(x)=n` and `length(b)=m`). You wish to solve it with constraints `x >= 0` (inequalities) and `sum(x)=1` (just one equality constraint). In my example, I'll take `A` random to simulate your problem but obviously, you are supposed to have it as well as `b` in some way corresponding to your problem.
```
m=20
n=10
A=matrix(rnorm(m*n), m, n)
x_exact=rnorm(n)
b=A%*%x_exact # simulate rhs b
u=diag(n) # here, inequality constraint matrix is just an identity matrix
co=double(n) # all 0, rhs of inequality such that u%*%x >= co <=> x >= 0
e=t(rep(1., n)) # equality constraint matrix, just one row of 1's
ce=1. # rhs of equality constraint, s.t. e%*%x=ce <=> sum(x)=1
# main call
x=nlsic::lsie_ln(A, b, u, co, e, ce)
# check the solution x for being >= 0 with some tolerance for round-off errors
stopifnot( all(x >= -1.e-10) )
# check for sum(x) = 1
stopifnot( abs(sum(x) - 1) <= 1.e-10 )

# if you need residual vector
res=A%*%x - b
```
Hoping this helps.

**Comment by spring-haru** [comment]
Many thanks. It helps a lot. In Python,
```
for i in range(1000):
    print('Thank you!')
```
